# -*- coding: utf-8 -*-
"""vizualisations_mg.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JDlhhyZLzqjGjqZ3gEEIrQEkl3MjHio8

# Visualisations for Master’s Thesis

This notebook explores the National Bibliography notated music dataset (1650–2025) and creates descriptive visualisations for the Master's Thesis "Visualising Notated Music Metadata from the Latvian National Bibliography" conducted within the RTU studies program RHMDB Digital Humanities.

## Setup (Google Colab + Google Drive)
"""
import pandas as pd
import plotly.express as px

from google.colab import drive
drive.mount('/content/gdrive')

import os
os.chdir("/content/gdrive/MyDrive/magistrs/data")


"""## Load the dataset"""
df = pd.read_csv('notated-music-dataset.csv',sep=',', low_memory=False)
# change year collum as integer
df["full_year_008"] = df["full_year_008"].astype("Int64")

# checking the year column data type
df["full_year_008"].dtype

# renaminig the identification column
df = df.rename(columns={"ierakstu_id": "ID"})

# check how many records are there in the dateset by counting unique ID
df["ID"].nunique()

# create a copy of dataset where one row per bibliographic record (unique ID)
df_unique = df.drop_duplicates(subset=["ID"]).copy()


# Visualisations 
"""## Cataloguing agencies (MARC 040)"""

# define column names for MARC 040 fields used in the analysis
col_a = "Original cataloging agency(040_a)"
col_d = "Modifying agency(040_d)"
col_e = "RDA(040_e)"

"""### Original cataloguing agency"""

# using df_unique because original cataloguing agency is used one per record
top_orig = (
    df_unique[col_a] # select the Original cataloging agency(040_a) field
    .value_counts(dropna=True) # calculate frequency of each agency
    .reset_index(name="count") # make a DataFrame with a 'count' column
)

fig = px.bar(
    top_orig, # set values
    x="count", # name x axis
    y=col_a, # name y axis
    orientation="h", # define chart orientation
    title="Original Cataloguing Agencies (040$a)", # set chart title
    labels={"Original cataloging agency(040_a)": "Agency", "count": "Number of records"} # set chart labels
)
fig.show() # render chart

"""## Modifying agencies"""

# using df because modifyng cataloguing agency can be repeated
top_mod = (
    df[col_d] # select the Modifying agency(040_d) field
    .value_counts(dropna=True) # calculate frequency of each agency
    .reset_index(name="count") # make a DataFrame with a 'count' column
)

fig = px.bar(
    top_mod, # set values
    x="count", # name x axis
    y="Modifying agency(040_d)", # name y axis
    orientation="h", # define chart orientation
    title="Modifying Agencies (040$d)", # set chart title
    labels={"Modifying agency(040_d)": "Agency", "count": "Number of records"} # set chart labels
)

fig.show() # render chart

"""## Record in RDA standart"""

# using df_unique because rda value is used one per record
rda_counts = (
    df_unique[col_e] # select the RDA(040_e) field
    .fillna("Not specified") # replace missing values with "Not specified"
    .value_counts() # count the frequency of each RDA value
    .reset_index(name="count") # make a DataFrame with a 'count' column
)

fig = px.pie(
    rda_counts, # set values
    names="RDA(040_e)", # RDA values
    values="count",  # number of records
    title="Use of RDA in Notated Music Records (040$e)", # set chart title
)
fig.show()# render chart

# creating a matrix showing the relationship between original and modifying cataloguing agencies
# using df because the modifying agency may appaer multiple times per record
matrix = (
    df.groupby([col_a, col_d])["ID"] # group by original and modifying agencies
    .nunique() # count unique bibliographic records per agency pair
    .reset_index(name="count")# make a DataFrame with a 'count' column
)

fig = px.density_heatmap(
    matrix, # set values
    x=col_d, # name x axis
    y=col_a, # name y axis
    z="count", # use "count" as z axis
    title="Original Agency vs. Modifying Agency", # set chart title
    labels={ # set chart labels
        col_a: "Original Agency",
        col_d: "Modifying Agency",
        "count": "Records"
    },
    color_continuous_scale="Cividis" # set colour for the scale
)

fig.update_layout(height=700) # set chart height
fig.show() # render chart
