# -*- coding: utf-8 -*-
"""vizualisations_mg.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JDlhhyZLzqjGjqZ3gEEIrQEkl3MjHio8

# Visualisations for Master’s Thesis

This notebook explores the National Bibliography notated music dataset (1650–2025) and creates descriptive visualisations for the Master's Thesis "Visualising Notated Music Metadata from the Latvian National Bibliography" conducted within the RTU studies program RHMDB Digital Humanities.

## Setup (Google Colab + Google Drive)
"""
import pandas as pd
import plotly.express as px

from google.colab import drive
drive.mount('/content/gdrive')

import os
os.chdir("/content/gdrive/MyDrive/magistrs/data")


"""## Load the dataset"""
df = pd.read_csv('notated-music-dataset.csv',sep=',', low_memory=False)
# change year collum as integer
df["full_year_008"] = df["full_year_008"].astype("Int64")

# checking the year column data type
df["full_year_008"].dtype

# renaminig the identification column
df = df.rename(columns={"ierakstu_id": "ID"})

# check how many records are there in the dateset by counting unique ID
df["ID"].nunique()

# create a copy of dataset where one row per bibliographic record (unique ID)
df_unique = df.drop_duplicates(subset=["ID"]).copy()


# Visualisations 
"""## Contributers and Resposibilities"""

persons_col = "persons (100 7XX)"

# using df because persons can be repeated
person_counts = (
    df[persons_col] # select the persons (100 7XX) field
    .value_counts(dropna=True) # calculate frequency of person
    .reset_index(name="count") # make a DataFrame with a 'count' column
)

fig = px.bar(
    person_counts.head(30), # set values of top 30 contributers
    x="count", # name x axis
    y="persons (100 7XX)", # name y axis
    orientation="h", # define chart orientation
    title="Top 30 Most Frequently Mentioned Persons in Notated Music Records",# set chart title
    labels={"persons (100 7XX)":"Person", "count": "Number of Records"}
)
# set chart height
fig.update_layout(height=900)
fig.show()# render chart

roles_col = "resposibility of persons (100,7XX_4)"

# counting the frequency of person–role combinations
# using df because the roles can be repeated
role_counts = (
    df[[roles_col, persons_col]]
    .value_counts(dropna=True) # calculate frequency of each pair
    .reset_index(name="count") # make a DataFrame with a 'count' column
)

top_people = (
    role_counts.groupby(persons_col)["count"] # grouping role counts by person
    .sum() # aggregating counts per person
    .sort_values(ascending=False)
    .head(50) # selectin top 50 persons
    .reset_index(name="count") # make a DataFrame with a 'count' column
)
# filteing the dataset to include only the top 50 persons
top_df = role_counts[role_counts[persons_col].isin(top_people[persons_col])]

# creating a bar chart showing role composition of the Top 50 persons
fig = px.bar(
    top_df, # set values
    x=persons_col, # name x axis
    y="count", # name y axis
    color="resposibility of persons (100,7XX_4)",  # set colors by unique roles
    title="Role Composition of Top Persons", # set chart title
    labels={
        "persons (100 7XX)": "Person", # set horizontal axis label
        "count": "Number of records", # set vertical axis label
        "resposibility of persons (100,7XX_4)": "Roles" # set label for role groups
    }
)
# adjusting layout for readability
fig.update_layout(xaxis_tickangle=-45, height=700)
fig.show() # render chart