# -*- coding: utf-8 -*-
"""vizualisations_mg.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JDlhhyZLzqjGjqZ3gEEIrQEkl3MjHio8

# Visualisations for Master’s Thesis

This notebook explores the National Bibliography notated music dataset (1650–2025) and creates descriptive visualisations for the Master's Thesis "Visualising Notated Music Metadata from the Latvian National Bibliography" conducted within the RTU studies program RHMDB Digital Humanities.

## Setup (Google Colab + Google Drive)
"""
import pandas as pd

from google.colab import drive
drive.mount('/content/gdrive')

import os
os.chdir("/content/gdrive/MyDrive/magistrs/data")


"""## Load the dataset"""
df = pd.read_csv('notated-music-dataset.csv',sep=',', low_memory=False)
# change year collum as integer
df["full_year_008"] = df["full_year_008"].astype("Int64")

# checking the year column data type
df["full_year_008"].dtype

# renaminig the identification column
df = df.rename(columns={"ierakstu_id": "ID"})

# check how many records are there in the dateset by counting unique ID
df["ID"].nunique()

# create a copy of dataset where one row per bibliographic record (unique ID)
df_unique = df.drop_duplicates(subset=["ID"]).copy()



"""## Data validation checks

Year from 008 vs Year from 260/264$c
"""

# converting year fields to strings for literal comparison as the value can contain different symbols and phrases
df_unique["full_year_008"] = df_unique["full_year_008"].astype(str)
df_unique["Date of publication(260_c_un_2641_c)"] = df_unique["Date of publication(260_c_un_2641_c)"].astype(str)

# using df_unique because there is one year per record
df_unique["validated"] = df_unique["full_year_008"] == df_unique["Date of publication(260_c_un_2641_c)"]

# counting matches and mismatches (records where both values exist and are compared)
matches = df_unique["validated"].sum()
mismatches = (df_unique["validated"] == False).sum()
missing = df_unique["validated"].isna().sum()
total = len(df_unique)

# calculating percentages
perc_matches = round(matches / total * 100, 1)
perc_mismatches = round(mismatches / total * 100, 1)
perc_missing = round(missing / total * 100, 1)

# returning results
print("Total records:", total)
print("Matching years:", matches, f"({perc_matches}%)")
print("Mismatched years:", mismatches, f"({perc_mismatches}%)")
print("Missing values:", missing, f"({perc_missing}%)")

# inspecting mismatched records
df_mismatch = df_unique[ df_unique["validated"] == False]

df_mismatch[["ID", "full_year_008", "Date of publication(260_c_un_2641_c)"]].head(20)

# selecting mismatched records and keep only relevant columns
df_mismatch = df_unique[df_unique["validated"] == False][
    ["ID", "full_year_008", "Date of publication(260_c_un_2641_c)"]
]
# saving mismatched records to a CSV file
df_mismatch.to_csv(
    "year_mismatches.csv",
    index=False,
    encoding="utf-8"
)