# -*- coding: utf-8 -*-
"""vizualisations_mg.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JDlhhyZLzqjGjqZ3gEEIrQEkl3MjHio8

# Visualisations for Master’s Thesis

This notebook explores the National Bibliography notated music dataset (1650–2025) and creates descriptive visualisations for the Master's Thesis "Visualising Notated Music Metadata from the Latvian National Bibliography" conducted within the RTU studies program RHMDB Digital Humanities.

## Setup (Google Colab + Google Drive)
"""
import pandas as pd
import plotly.express as px
import matplotlib.pyplot as plt
import seaborn as sns

from google.colab import drive
drive.mount('/content/gdrive')

import os
os.chdir("/content/gdrive/MyDrive/magistrs/data")


"""## Load the dataset"""
df = pd.read_csv('notated-music-dataset.csv',sep=',', low_memory=False)
# change year collum as integer
df["full_year_008"] = df["full_year_008"].astype("Int64")

# checking the year column data type
df["full_year_008"].dtype

# renaminig the identification column
df = df.rename(columns={"ierakstu_id": "ID"})

# check how many records are there in the dateset by counting unique ID
df["ID"].nunique()

# create a copy of dataset where one row per bibliographic record (unique ID)
df_unique = df.drop_duplicates(subset=["ID"]).copy()

"""## Field completeness (grouped dataset)
This uses a pre-grouped file (`notated-music-dataset-grouped.csv`) where each row represents a record and columns represent MARC fields/groups.

The goal is to see which fields are most often filled and how missingness looks across a sample of records.
"""

df_filtered = pd.read_csv('notated-music-dataset-grouped.csv',sep=',', low_memory=False)
df_filtered = df_filtered.replace("NA", None)

print("Grouped dataset rows, columns:", df_filtered.shape)
df_filtered.head()

# replacing string "NA" values with missing values
df_filtered = df_filtered.replace("NA", None)

id_col = "ierakstu_id"

# selecting all metadata fields except record ID
all_fields = [col for col in df_filtered.columns if col != id_col]

# determining presence of each field per record
presence_by_record = (
    df_filtered[all_fields]
    .notna()
    .groupby(df_filtered[id_col])
    .any()
)

# calculating percentage of records containing each field
field_usage = (presence_by_record.mean() * 100).round(1)
field_usage = field_usage.sort_values(ascending=False).reset_index()
field_usage.columns = ["field", "percent_filled"] # renaming columns

fig = px.bar(
    field_usage, # set values
    x="percent_filled", # name x axis
    y="field", # name y axis
    orientation="h", # define chart orientation
    title="Field Usage per Record (% of records containing the feld)", # set chart title
    labels={
        "percent_filled": "Percentage filled", # set horizontal axis label
    }
)
# set chart height
fig.update_layout(height=3000)
fig.show() # render chart

# random sample of 300 records to improve readability of the heatmap
sample = presence_by_record.sample(300, random_state=42)
# creating a heatmap showing missing fields for the sampled records
plt.figure(figsize=(20, 12))
sns.heatmap(~sample, cmap="crest", cbar=False) # True/False values are inverted (~) so that missing fields are highlighted
plt.title("Missing Fields per Record (Sample Records)") # set chart title
plt.xlabel("Fields") # set horizontal axis label
plt.ylabel("Record ID")  # set vertical axis label
plt.show() # render chart
#plt.savefig("missing_fields_sample_records.png", dpi=200, bbox_inches="tight")
#plt.close()

# creating a heatmap showing missing fields for all records
plt.figure(figsize=(20, 30))
ax = sns.heatmap(~presence_by_record, cbar=False, rasterized=True) # invert presence to highlight missing fields
plt.title("Missing Fields per Record – All 17 726 Records") # set chart title
plt.xlabel("Fields") # set horizontal axis label
plt.ylabel("Record ID" ) # set vertical axis label
# saving the heatmap to file
plt.savefig("missing_fields_all_records.png", dpi=200, bbox_inches="tight")
plt.close() # save chart