# -*- coding: utf-8 -*-
"""vizualisations_mg.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JDlhhyZLzqjGjqZ3gEEIrQEkl3MjHio8

# Visualisations for Master’s Thesis

This notebook explores the National Bibliography notated music dataset (1650–2025) and creates descriptive visualisations for the Master's Thesis "Visualising Notated Music Metadata from the Latvian National Bibliography" conducted within the RTU studies program RHMDB Digital Humanities.

## Setup (Google Colab + Google Drive)
"""
import pandas as pd
import plotly.express as px

from google.colab import drive
drive.mount('/content/gdrive')

import os
os.chdir("/content/gdrive/MyDrive/magistrs/data")


"""## Load the dataset"""
df = pd.read_csv('notated-music-dataset.csv',sep=',', low_memory=False)
# change year collum as integer
df["full_year_008"] = df["full_year_008"].astype("Int64")

# checking the year column data type
df["full_year_008"].dtype

# renaminig the identification column
df = df.rename(columns={"ierakstu_id": "ID"})

# check how many records are there in the dateset by counting unique ID
df["ID"].nunique()

# create a copy of dataset where one row per bibliographic record (unique ID)
df_unique = df.drop_duplicates(subset=["ID"]).copy()


# Visualisations 
"""## Language of publication (008/35)"""

df_unique["language(008)"].nunique() # returns count of unique values

# using df_unique because the language value is used only one per record in the controlled field 008
lang_counts = (
    df_unique["language(008)"] # select the language(008) field
    .value_counts()  # count the frequency of language
    .reset_index() # reset the index of the DataFrame
)

lang_counts.columns = ["language", "count"] # rename columns

# initialize bar chart
fig = px.bar(
    lang_counts, # set values
    x="count", # name x axis
    y="language", # name y axis
    orientation="h", # define chart orientation
    title="Languages in National Bibliography Notated Music Publications", # set chart title
    labels={"count": "Number of Records"} # set chart labels
)
# set chart height
fig.update_layout(height=700)
fig.show() # render chart

"""### Top 10 languages + 'Other'"""

# creating a top 10 languages and grouping together less frequent used langauges as "Other"
top10_lang = lang_counts.head(10) # selecting top 10 most frequent languages
other_sum_lang = lang_counts["count"].iloc[10:].sum() # selecting languages that are not in the top 10
other_row_lang = pd.DataFrame([{"language": "Other", "count": other_sum_lang}]) # creating a new row representing all less frequent languages grouped as "Other"

top10_with_other_lang = pd.concat([top10_lang,other_row_lang], ignore_index=True) # combining the Top 10 languages with the aggregated "Other" category into one DataFrame

# create a bar chart showing the distrubution of top 10 most frequent languages and less frequent languages grouped as "Other"
fig = px.bar(
    top10_with_other_lang, # set values
    x="count", # name x axis
    y="language", # name y axis
    orientation="h",  # define chart orientation
    title="Top 10 Languages in Notated Music Publications (with 'Other')", # set chart title
    labels={"count": "Number of Records"} # set chart labels
)
fig.show() # render chart

"""### Language composition over time (Top 10 + Other, normalized)"""

# extract the languages of the Top 10 most frequent languages
top10_langs = lang_counts.head(10)["language"]

# assign to lang_year variable the amount of unique ID count per language per year
lang_year = (
    df_unique.groupby(["full_year_008", "language(008)"])["ID"] # group by year and language
    .nunique() # return unique value count
    .reset_index(name="count") # rename nunique() result to "count"
)

# Collapse langauge(008) records which are not in top 10 into "Other"
lang_year["language_group"] = lang_year["language(008)"].where(
    lang_year["language(008)"].isin(top10_langs),
    "Other"
)

lang_year_top = (
    lang_year.groupby(["full_year_008", "language_group"])["count"] # group by year and language group
    .sum() # sum publication counts within each group
    .reset_index() # return grouped keys as columns
)

# create a normalized stacked area chart showing the proportion of publications per language group over time
fig = px.area(
    lang_year_top,
    x="full_year_008", # use "full_year_008" column values as horizontal axis
    y="count", # use "count" column values as vertical axis
    color="language_group", # set colors by unique language groups
    groupnorm="percent", # normalize counts per year to show proportions
    title="Language Composition of Notated Music Publications Over Time (Top 10 + Other, Normalized)",
    labels={
        "full_year_008": "Year", # set horizontal axis label
        "count": "Proportion of Publications", # set vertical axis label
        "language_group": "Language" # set label for language groups
    },
)

# set chart width, height and title
fig.update_layout(
    width=1300,
    height=600,
    legend_title="Language"
)
fig.show() # render chart