# -*- coding: utf-8 -*-
"""vizualisations_mg.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JDlhhyZLzqjGjqZ3gEEIrQEkl3MjHio8

# Visualisations for Master’s Thesis

This notebook explores the National Bibliography notated music dataset (1650–2025) and creates descriptive visualisations for the Master's Thesis "Visualising Notated Music Metadata from the Latvian National Bibliography" conducted within the RTU studies program RHMDB Digital Humanities.

## Setup (Google Colab + Google Drive)
"""
import pandas as pd
import plotly.express as px
import plotly.graph_objects as go
import networkx as nx

from google.colab import drive
drive.mount('/content/gdrive')

import os
os.chdir("/content/gdrive/MyDrive/magistrs/data")


"""## Load the dataset"""
df = pd.read_csv('notated-music-dataset.csv',sep=',', low_memory=False)
# change year collum as integer
df["full_year_008"] = df["full_year_008"].astype("Int64")

# checking the year column data type
df["full_year_008"].dtype

# renaminig the identification column
df = df.rename(columns={"ierakstu_id": "ID"})

# check how many records are there in the dateset by counting unique ID
df["ID"].nunique()

# create a copy of dataset where one row per bibliographic record (unique ID)
df_unique = df.drop_duplicates(subset=["ID"]).copy()


"""## Network graph of authors and their works"""

author_col = "contained_work_author (700 12)"
work_col   = "contained_work(700_12)"

# using df because authors can be repeated
df_aw = df[["ID", author_col, work_col]].dropna().copy() # keeping only rows where both author and contained work title exist

# creating an edge list for author and work pairs
edges_df = (
    df_aw[[author_col, work_col]]
    .rename(columns={author_col: "author", work_col: "work"})
    .drop_duplicates()# droping duplicates so the same author-work pair is not counted multiple times
)

# preparing node lists
authors = edges_df["author"].unique() # authors are extracted from the edge list
works   = edges_df["work"].unique() # works are extracted from the edge list

# building the graph
G_aw = nx.Graph()
G_aw.add_nodes_from(authors, ntype="Authors")
G_aw.add_nodes_from(works, ntype="Work")

# adding edges between authors and their contained works
for _, row in edges_df.iterrows():
    G_aw.add_edge(row["author"], row["work"])
# returning basic information about the network
print("Nodes:", G_aw.number_of_nodes(), "Edges:", G_aw.number_of_edges())

# computing layout
pos_aw = nx.spring_layout(G_aw, k=0.5, iterations=80, seed=42)

# preparing line segments for network edges
edge_x, edge_y = [], []
for u, v in G_aw.edges():
    x0, y0 = pos_aw[u] # position of first node
    x1, y1 = pos_aw[v] # position of second node
    edge_x += [x0, x1, None]
    edge_y += [y0, y1, None]

# creating a Plotly trace for edges
edge_trace = go.Scatter(
    x=edge_x,
    y=edge_y,
    mode="lines",
    line=dict(width=2.5, color="rgba(80,80,80,0.3)"),
    hoverinfo="none",
    showlegend=False,
)
# preparing coordinates for author nodes
author_x = [pos_aw[n][0] for n in authors]
author_y = [pos_aw[n][1] for n in authors]

# creating a Plotly trace for author nodes
author_trace = go.Scatter(
    x=author_x,
    y=author_y,
    mode="markers",
    name="Author",
    hoverinfo="text",
    text=authors,
    marker=dict(
        color="#377eb8",
        size=14,
        symbol="circle",
        line=dict(width=1, color="white"),
        opacity=0.9,
    ),
)
# preparing coordinates for work nodes
work_x = [pos_aw[n][0] for n in works]
work_y = [pos_aw[n][1] for n in works]

# creating a Plotly trace for work nodes
work_trace = go.Scatter(
    x=work_x,
    y=work_y,
    mode="markers",
    name="Work (contained title)",
    hoverinfo="text",
    text=works,
    marker=dict(
        color="#e41a1c",
        size=10,
        symbol="square",
        line=dict(width=1, color="white"),
        opacity=0.9,
    ),
)

# combining all traces into a single visualization
fig = go.Figure(
    data=[edge_trace, author_trace, work_trace],
    layout=go.Layout(
        title="Author–Work Network",
        title_x=0.5,
        showlegend=True,
        hovermode="closest",
        margin=dict(b=20, l=5, r=5, t=40),
        xaxis=dict(showgrid=False, zeroline=False, showticklabels=False),
        yaxis=dict(showgrid=False, zeroline=False, showticklabels=False),
    ),
)
# set graph width, height
fig.update_layout(width=1100, height=800)
fig.show() # render graph