# -*- coding: utf-8 -*-
"""vizualisations_mg.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JDlhhyZLzqjGjqZ3gEEIrQEkl3MjHio8

# Visualisations for Master’s Thesis

This notebook explores the National Bibliography notated music dataset (1650–2025) and creates descriptive visualisations for the Master's Thesis "Visualising Notated Music Metadata from the Latvian National Bibliography" conducted within the RTU studies program RHMDB Digital Humanities.

## Setup (Google Colab + Google Drive)
"""
import pandas as pd
import plotly.express as px

from google.colab import drive
drive.mount('/content/gdrive')

import os
os.chdir("/content/gdrive/MyDrive/magistrs/data")


"""## Load the dataset"""
df = pd.read_csv('notated-music-dataset.csv',sep=',', low_memory=False)
# change year collum as integer
df["full_year_008"] = df["full_year_008"].astype("Int64")

# checking the year column data type
df["full_year_008"].dtype

# renaminig the identification column
df = df.rename(columns={"ierakstu_id": "ID"})

# check how many records are there in the dateset by counting unique ID
df["ID"].nunique()

# create a copy of dataset where one row per bibliographic record (unique ID)
df_unique = df.drop_duplicates(subset=["ID"]).copy()


# Visualisations 
"""## Notated music specific fields"""

### 008/23 Form of item


# using df_unique because the form of item value is used only one per record in the controlled field 008
form_counts = (
    df_unique["Form of item(008)"] # select the Form of Item (008/23) field
    .value_counts(dropna=True) # count the frequency of each form
    .reset_index(name="count") # make a DataFrame with a 'count' column
)
form_counts.columns = ["Form of item", "count"] # rename columns

fig = px.bar(
    form_counts, # set values
    x="count", # name x axis
    y="Form of item",  # name y axis
    orientation="h",  # define chart orientation
    title="Distribution of Form of Item (MARC 008/23)", # set chart title
    labels={"count": "Number of Records"}  # set chart labels
)
fig.show() # render chart

"""### 008/22 Target audience"""

# using df_unique because the target audience value is used only one per record in the controlled field 008
audience_counts = (
    df_unique["Target audience(008)"] # select the Target audience(008) field
    .value_counts() # count the frequency of each value
    .reset_index(name="count") # make a DataFrame with a 'count' column
)
audience_counts.columns = ["Target audience", "count"] # rename columns

fig = px.bar(
    audience_counts, # set values
    x="count", # name x axis
    y="Target audience", # name y axis
    orientation="h", # define chart orientation
    title="Target Audience Codes in Notated Music (MARC 008/22)", # set chart title
    labels={"count": "Number of Records"}  # set chart labels
)
fig.show() # render chart

"""### 008/21 Music parts"""

# using df_unique because the music part value is used only one per record in the controlled field 008
parts_counts = (
    df_unique["Music parts(008)"] # select the Music parts(008) field
    .value_counts(dropna=True) # count the frequency of each music part value
    .reset_index(name="count") # make a DataFrame with a 'count' column
)
parts_counts.columns = ["Music parts", "count"] # rename column

fig = px.bar(
    parts_counts, # set values
    x="count", # name x axis
    y="Music parts", # name y axis
    orientation="h", # define chart orientation
    title="Music Parts Information (MARC 008/21)", # set chart title
    labels={"count": "Number of Records"}  # set chart labels
)
fig.show() # render chart

"""### Composition format (008/18–19)"""

# using df_unique because the composition format value is used only one per record in the controlled field 008
comp_counts = (
    df_unique["compostion_format(008)"] # select the compostion_format(008) field
    .value_counts(dropna=True) # count the frequency of each value exluding missing values
    .reset_index(name="count") # make a DataFrame with a 'count' column
)

fig = px.bar(
    comp_counts,  # set values
    x="count", # name x axis
    y="compostion_format(008)", # name y axis
    orientation="h", # define chart orientation
    title="All Composition Format Codes (MARC 008/18–19)", # set chart title
    labels={"count": "Number of Records", "compostion_format(008)": "Composition format"}  # set chart labels
)
fig.show() # render chart

# selecting the top 10 composition formats
top10_comp = comp_counts.head(10)

fig = px.bar(
    top10_comp, # set values
    x="count", # name x axis
    y="compostion_format(008)", # name y axis
    orientation="h", # define chart orientation
    title="Top 10 Composition Format Codes (MARC 008/18–19)", # set chart title
    labels={"count": "Number of Records", "compostion_format(008)": "Composition format"}  # set chart labels
)
fig.show() # render chart

# selecting the least frequent 10 composition formats
last10_comp = comp_counts.tail(10)

fig = px.bar(
    last10_comp, # set values
    x="count", # name x axis
    y="compostion_format(008)", # name y axis
    orientation="h", # define chart orientation
    title="Last 10 Composition Format Codes (MARC 008/18–19)", # set chart title
    labels={"count": "Number of Records", "compostion_format(008)": "Composition format"}  # set chart labels
)
fig.show() # render chart

"""### Music format (008/20)"""

# using df_unique because the music format value is used only one per record in the controlled field 008
format_counts = (
    df_unique["music_format(008)"] # select the music_format(008) field
    .value_counts(dropna=True) # count the frequency of each music format value
    .reset_index(name="count") # make a DataFrame with a 'count' column
)

fig = px.bar(
    format_counts, # set values
    x="count", # name x axis
    y="music_format(008)",  # name y axis
    orientation="h",  # define chart orientation
    title="Music Format (MARC 008/20)", # set chart title
    labels={"count": "Number of Records", "music_format(008)": "Music format"}  # set chart labels
)
fig.show() # render chart

"""## Instrumentation analytics (048)"""

col_048a = "instrument_group_ensamles(048_a)"
col_048b = "instrument_group_solo(048_b)"

# using df because 048 subfields ($$a and $$b) are repeatable per record
# identifying records that contain any instrumentation information (048)
has_048 = df[
    df[col_048a].notna() |
    df[col_048b].notna()
]
# identifying records that contain ensemble instrumentation information (048_a)
has_048a = df[
    df[col_048a].notna()
]
# identifying records that contain soloist instrumentation information (048_b)
has_048b = df[
    df[col_048b].notna()
]
# identifying records that contain both ensemble and soloist instrumentation information (048_a and 048_b)
has_both = df[
    df[col_048a ].notna() &
    df[col_048b].notna()
]

# summarizing the presence of instrumentation information
summary = {
    "Total records": len(df_unique), # total records are counted using df_unique because only one id is used per record
    "Records with ANY 048": len(has_048),
    "Records with 048$$a (ensemble)": len(has_048a),
    "Records with 048$$b (soloist)": len(has_048b),
    "Records with both 048$$a and 048$$b": len(has_both),
}
summary

"""### Ensembles (048$$a)"""

ensemble_counts = (
    df[col_048a] # select the instrument_group_ensamles(048_a) field
    .value_counts(dropna=True) #calculate frequency of instrumental group
    .reset_index(name="count") # make a DataFrame with a 'count' column
)

fig = px.bar(
    ensemble_counts, # set values
    x="count", # name x axis
    y="instrument_group_ensamles(048_a)", # name y axis
    orientation="h", # define chart orientation
    title="Ensemble Groups in Latvian Notated Music (MARC 048$$a)", # set chart title
    labels={"instrument_group_ensamles(048_a)": "Instrument Group", "count": "Number of records"} # set chart labels
)
fig.show() # render chart

"""#### Ensembles over time (048$$a)"""

# selecting records that contain ensemble instrumentation values
df48a = df[df[col_048a].notna()].copy()

counts48a = (
    df48a.groupby(["full_year_008", "instrument_group_ensamles(048_a)"])["ID"] # grouping records by publication year and ensemble instrument group
    .nunique() # counting unique bibliographic records
    .reset_index(name="count") # make a DataFrame with a 'count' column
)

fig = px.area(
    counts48a, # set values
    x="full_year_008", # name x axis
    y="count", # name y axis
    color="instrument_group_ensamles(048_a)", # set colors by unique instrumental groups
    groupnorm="percent",  # normalize counts per year to show proportions
    title="Ensemble Groups Over Time (Normalized Share per Year)", # set chart title
    labels={
        "full_year_008": "Year", # set horizontal axis label
        "count": "Proportion of Publications", # set vertical axis label
    },
)
# set chart width, height and title
fig.update_layout(
    width=1300,
    height=600,
    legend_title="Instrument group"
)
fig.show() # render chart

"""### Soloists (048$$b)"""

solo_counts = (
    df[col_048b] # select the instrument_group_ensamles(048_a) field
    .value_counts(dropna=True) #calculate frequency of instrumental group
    .reset_index(name="count") # make a DataFrame with a 'count' column
)

fig = px.bar(
    solo_counts, # set values
    x="count", # name x axis
    y="instrument_group_solo(048_b)", # name y axis
    orientation="h", # define chart orientation
    title="Solo Instruments/Voices in Latvian Notated Music (MARC 048$$b)",  # set chart title
    labels={"instrument_group_solo(048_b)": "Instrument Group", "count": "Number of records"}  # set chart labels
)
fig.show() # render chart

"""#### Soloists over time (048$$a)"""

# selecting records that contain soloists instrumentation values
df48b = df[df[col_048b].notna()].copy()

counts48b = (
    df48b.groupby(["full_year_008", "instrument_group_solo(048_b)"])["ID"] # grouping records by publication year and ensemble instrument group
    .nunique() # counting unique bibliographic records
    .reset_index(name="count") # make a DataFrame with a 'count' column
)

fig = px.area(
    counts48b,  # set values
    x="full_year_008",  # name x axis
    y="count", # name y axis
    color="instrument_group_solo(048_b)",  # set colors by unique instrumental groups
    groupnorm="percent",  # normalize counts per year to show proportions
    title="Solo Instruments/Voices Over Time (Normalized Share per Year)", # set chart title
    labels={
        "full_year_008": "Year", # set horizontal axis label
        "count": "Proportion of Publications", # set vertical axis label
    },
)
# set chart width, height and title
fig.update_layout(
    width=1300,
    height=600,
    legend_title="Instrument group"
)
fig.show() # render chart