# -*- coding: utf-8 -*-
"""vizualisations_mg.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JDlhhyZLzqjGjqZ3gEEIrQEkl3MjHio8

# Visualisations for Master’s Thesis

This notebook explores the National Bibliography notated music dataset (1650–2025) and creates descriptive visualisations for the Master's Thesis "Visualising Notated Music Metadata from the Latvian National Bibliography" conducted within the RTU studies program RHMDB Digital Humanities.

## Setup (Google Colab + Google Drive)
"""
import pandas as pd
import plotly.express as px

from google.colab import drive
drive.mount('/content/gdrive')

import os
os.chdir("/content/gdrive/MyDrive/magistrs/data")


"""## Load the dataset"""
df = pd.read_csv('notated-music-dataset.csv',sep=',', low_memory=False)
# change year collum as integer
df["full_year_008"] = df["full_year_008"].astype("Int64")

# checking the year column data type
df["full_year_008"].dtype

# renaminig the identification column
df = df.rename(columns={"ierakstu_id": "ID"})

# check how many records are there in the dateset by counting unique ID
df["ID"].nunique()

# create a copy of dataset where one row per bibliographic record (unique ID)
df_unique = df.drop_duplicates(subset=["ID"]).copy()

"""## Publication places on a map"""

place_col = "Place of publication (260_a_un_2641_a)"

# using df because publication places are repeatable per record
df_places=(
    df[place_col] # select the Place of publication (260_a_un_2641_a) field
    .value_counts(dropna=True) # calculate frequency of each place
    .reset_index(name="count") # make a DataFrame with a 'count' column
)
# returning places as a list so it can be copied
print(df_places['Place of publication (260_a_un_2641_a)'].tolist())

# creating a dictionary for each place providing geographical coordinated from WikiData
city_coords = {
    "Riga": (56.9475, 24.106944),
    "Liepāja": (56.508333, 21.011111),
    "Jelgava": (56.652222, 23.724444),
    "Rēzekne": (56.506667, 27.330833),
    "Daugavpils": (55.871389, 26.516111),
    "Ogre": (56.816944, 24.604722),
    "Ventspils": (57.389722, 21.564444),
    "Priekule": (56.447222, 21.593333),
    "Saldus": (56.666667, 22.493611),
    "Dobele": (56.625833, 23.281111),
    "Madona": (56.854167, 26.220556),
    "Valmiera": (57.538056, 25.423056),
    "Balvi": (57.129167, 27.266667),
    "Aizkraukle": (56.600833, 25.255),
    "Talsi": (57.244722, 22.588889),
    "Valka": (57.775278, 26.021389),
    "Cēsis": (57.313056, 25.274722),
    "Murjāņi": (57.133056, 24.664167),
    "Sīkrags": (57.66, 22.226389),
    "Saulkrasti": (57.263611, 24.416389),
    "Rūjiena": (57.896944, 25.326111),
    "Salaspils Municipality": (56.851667, 24.350556),
    "Limbaži": (57.514722, 24.713056),
    "Mārupe": (56.906944, 24.0575),
    "Kurmāle Parish": (56.909715, 21.85467),
    "Ikšķile": (56.836667, 24.496389),
    "Viļāni": (56.552778, 26.925278),
    "Jūrmala": (56.9665, 23.722111),
    "Sigulda": (57.153889, 24.854444),
    "Tukums": (56.96879, 23.15352),
    "Smiltene": (57.424167, 25.906389),
    "Ērgļi": (56.8975, 25.6375),
    "Sēja Municipality": (57.152778, 24.644444),
    "Gulbene": (57.175, 26.756389),
    "Alūksne Municipality": (57.3833, 27.1),
    "Jaunpiebalga Parish": (57.145073, 26.02327),
    "Kandava": (57.036389, 22.776111),
    "Preiļi": (56.294167, 26.724722),
    "Upesciems": (56.981944, 24.3375),
    "Rauna Parish": (57.341774, 25.640943),
    "Kuldīga": (56.967222, 21.97),
    "Jaunjelgava": (56.6175, 25.081389),
    "Inčukalns": (57.096389, 24.6875),
    "South Kurzeme Municipality": (56.55, 21.15),
    "Lielvārde": (56.7175, 24.810556),
    "Liezēre Parish": (57.01849, 26.034172),
    "Līvāni": (56.353889, 26.176111),
    "Ropaži Municipality": (57, 24.5),
    "Zeltiņi Parish": (57.349004, 26.76718),
    "Tallinn": (59.437222, 24.745),
    "Berlin": (52.516667, 13.383333),
    "Dresden": (51.049329, 13.738144),
    "Frankfurt": (50.110556, 8.682222),
    "Warsaw": (52.23, 21.011111),
    "Leipzig": (51.340632, 12.374733),
    "New York City": (40.712778, -74.006111),
    "Saint Petersburg": (59.95, 30.316667),
    "Nordstemmen": (52.160489, 9.783867),
    "Toronto": (43.670278, -79.386667),
    "Thessaloniki": (40.640278, 22.935556),
    "Esslingen am Neckar": (48.740556, 9.310833),
    "Basel": (47.560556, 7.590556),
    "Offenbach am Main": (50.1, 8.766667),
    "Moscow": (55.750556, 37.6175),
    "Chemnitz": (57.313056, 25.274722),
    "London": (51.507222, -0.1275),
    "Munich": (48.1375, 11.575),
    "Vienna": (48.208333, 16.3725),
    "Latvia": (57, 25),
    "Soviet Union": (65, 90),
    "United States": (39.828175, -98.5795)
}

# creating a list of places with geographic coordinates
places = []
for _, row in df_places.iterrows(): # iterating through the table of publication places
    place = row["Place of publication (260_a_un_2641_a)"]  # publication place name
    if place in city_coords: # checking whether coordinates are available for the given place
        lat, lon = city_coords[place] # retrieving latitude and longitude
        places.append({"place": place, "count": row["count"], "lat": lat, "lon": lon})  # storing place name, record count, and coordinates
# converting the list of places into a DataFrame for mapping and visualization
places_df = pd.DataFrame(places)

# creating a geographic scatter map showing publication places
fig = px.scatter_geo(
    places_df,
    lat="lat", # latitude of publication place
    lon="lon", # longitude of publication place
    color="count", # number of publications
    hover_name="place", # display place name on hover
    projection="natural earth", # map projection
    title="Publication Places on a map<br>(Hover for publication place title, coordinates and count)" # set map title
)
# default map view for the geographic area of Latvia
fig.update_geos(
    lataxis_range=[55, 58],
    lonaxis_range=[20, 27]
)
# set  width, height
fig.update_layout(height=800, width=1200)
fig.show() # render map