# -*- coding: utf-8 -*-
"""vizualisations_mg.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JDlhhyZLzqjGjqZ3gEEIrQEkl3MjHio8

# Visualisations for Master’s Thesis

This notebook explores the National Bibliography notated music dataset (1650–2025) and creates descriptive visualisations for the Master's Thesis "Visualising Notated Music Metadata from the Latvian National Bibliography" conducted within the RTU studies program RHMDB Digital Humanities.

## Setup (Google Colab + Google Drive)
"""
import pandas as pd
import plotly.express as px

from google.colab import drive
drive.mount('/content/gdrive')

import os
os.chdir("/content/gdrive/MyDrive/magistrs/data")


"""## Load the dataset"""
df = pd.read_csv('notated-music-dataset.csv',sep=',', low_memory=False)
# change year collum as integer
df["full_year_008"] = df["full_year_008"].astype("Int64")

# checking the year column data type
df["full_year_008"].dtype

# renaminig the identification column
df = df.rename(columns={"ierakstu_id": "ID"})

# check how many records are there in the dateset by counting unique ID
df["ID"].nunique()

# create a copy of dataset where one row per bibliographic record (unique ID)
df_unique = df.drop_duplicates(subset=["ID"]).copy()


# Visualisations 
"""## Publishers"""

# creating a variable for the column
publisher_col = "Name of publisher (260_b_un_2641_b)"

# using df_unique because the publisher value is used only one per record
publisher_counts = (
    df_unique[publisher_col] # select unique publisher_col column
    .value_counts() # count occurences of unique publisher
    .reset_index(name="count") # make a DataFrame with a 'count' column
)
publisher_counts.columns = ["publisher", "count"] # rename columns

# function to classify year by time period for a given year parameter
def classify_era(year):
    if year < 1800:
        return "Pre-1800"
    elif 1800 <= year < 1900:
        return "19th century (1800–1900)"
    elif 1900 <= year < 1940:
        return "Early 20th century (1900–1940)"
    elif 1940 <= year < 1990:
        return "Soviet period (1940–1990)"
    else:
        return "Post-1991 (1991–2025)"

df_pub = df_unique[[publisher_col, "full_year_008"]].copy() # create a copy of DataFrame
df_pub["era"] = df_pub["full_year_008"].apply(classify_era) # create "era" column with value of classified time period

pub_era_counts = (
    df_pub
    .groupby(["era", publisher_col])[publisher_col]  # select a column to count
    .count() # count publication per group
    .reset_index(name="count") # convert result to DataFrame with column 'count'
)

top30_publishers = (
    pub_era_counts.groupby(publisher_col)["count"] # group by publisher count per era
    .sum() # sum publication counts accross all eras
    .sort_values(ascending=False) # sort in descending order
    .head(30) # select top 30 publishers by count
    .index # get top publisher names
)

# filter pub_era_counts to keep only rows for the top 30 publishers
pub_era_top = pub_era_counts[pub_era_counts[publisher_col].isin(top30_publishers)]

# create a heatmap showing the top 30 publisher activy over defined time periods
fig = px.density_heatmap(
    pub_era_top, # set values
    x="era", # name x axis
    y=publisher_col, # name y axis
    z="count", # use "count" as z axis
    color_continuous_scale="Blues", # define color scale
    title=f"Publisher Activity by Historical Period (Top 30 Publishers)", # set heatmap title
)
# set chart width, height, titles and scale colours
fig.update_layout(
    width=1200,
    height=900,
    xaxis_title="Historical Era",
    yaxis_title="Publisher",
    coloraxis_colorbar_title="Publications",
)
fig.show() # render chart