# -*- coding: utf-8 -*-
"""vizualisations_mg.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JDlhhyZLzqjGjqZ3gEEIrQEkl3MjHio8

# Visualisations for Master’s Thesis

This notebook explores the National Bibliography notated music dataset (1650–2025) and creates descriptive visualisations for the Master's Thesis "Visualising Notated Music Metadata from the Latvian National Bibliography" conducted within the RTU studies program RHMDB Digital Humanities.

## Setup (Google Colab + Google Drive)
"""
import pandas as pd
import plotly.express as px

from google.colab import drive
drive.mount('/content/gdrive')

import os
os.chdir("/content/gdrive/MyDrive/magistrs/data")


"""## Load the dataset"""
df = pd.read_csv('notated-music-dataset.csv',sep=',', low_memory=False)
# change year collum as integer
df["full_year_008"] = df["full_year_008"].astype("Int64")

# checking the year column data type
df["full_year_008"].dtype

# renaminig the identification column
df = df.rename(columns={"ierakstu_id": "ID"})

# check how many records are there in the dateset by counting unique ID
df["ID"].nunique()

# create a copy of dataset where one row per bibliographic record (unique ID)
df_unique = df.drop_duplicates(subset=["ID"]).copy()


# Visualisations 
# return the year range
df_unique["full_year_008"].min(), df_unique["full_year_008"].max()

# using df_unique because the year field is used only one per record
counts = (
    df_unique.groupby("full_year_008")["ID"] # group records by publication year
    .nunique()  # count unique bibliographic records per year
    .reset_index(name="n_publications") # convert result to a DataFrame
)

# create a line chart showing the number of notated music publications per year
fig = px.line(
    counts,  # set values
    x="full_year_008",  # publication year on the x-axis
    y="n_publications", # number of publications on the y-axis
    title="Number of Notated Music Publications per Year (1650–2025)", # set chart title
    labels={"full_year_008": "Year", # set horizontal axis label
            "n_publications": "Publications"}, # set vertical axis label
    template="simple_white"
)
# set chart width, height and range
fig.update_layout(
    width=2000,
    height=800,
    xaxis=dict(range=[1650, 2050]), # fixed range to show long-term trends clearly
)
fig.show() # render chart