# -*- coding: utf-8 -*-
"""vizualisations_mg.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JDlhhyZLzqjGjqZ3gEEIrQEkl3MjHio8

# Visualisations for Master’s Thesis

This notebook explores the National Bibliography notated music dataset (1650–2025) and creates descriptive visualisations for the Master's Thesis "Visualising Notated Music Metadata from the Latvian National Bibliography" conducted within the RTU studies program RHMDB Digital Humanities.

## Setup (Google Colab + Google Drive)
"""
import pandas as pd
import plotly.express as px

from google.colab import drive
drive.mount('/content/gdrive')

import os
os.chdir("/content/gdrive/MyDrive/magistrs/data")


"""## Load the dataset"""
df = pd.read_csv('notated-music-dataset.csv',sep=',', low_memory=False)
# change year collum as integer
df["full_year_008"] = df["full_year_008"].astype("Int64")

# checking the year column data type
df["full_year_008"].dtype

# renaminig the identification column
df = df.rename(columns={"ierakstu_id": "ID"})

# check how many records are there in the dateset by counting unique ID
df["ID"].nunique()

# create a copy of dataset where one row per bibliographic record (unique ID)
df_unique = df.drop_duplicates(subset=["ID"]).copy()


# Visualisations 

"""## Topical Term subjects"""

# using df because the subjects can be repeated
subj_counts = (
    df["Topical Term (650)"] # select the Topical Term (650) field
    .value_counts(dropna=True) # calculate frequency of each agency
    .reset_index(name="count") # make a DataFrame with a 'count' column
)
fig = px.bar(
    subj_counts.head(30), # set values of top 30 subjects
    x="count", # name x axis
    y="Topical Term (650)", # name y axis
    orientation="h", # define chart orientation
    title="Top 30 Subject Terms in Latvian Notated Music Records", # set chart title
    labels={"count": "Number of records", "subject": "Subject term"} # set chart labels
)
# set chart height
fig.update_layout(height=900)
fig.show()# render chart

df["Topical Term (650)"].nunique()

fig = px.treemap(
    subj_counts.head(50),
    path=["Topical Term (650)"],
    values="count",
    title="Top 50 Most Common Subject Terms (Treemap)"
)
fig.show()
