# -*- coding: utf-8 -*-
"""vizualisations_mg.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JDlhhyZLzqjGjqZ3gEEIrQEkl3MjHio8

# Visualisations for Master’s Thesis

This notebook explores the National Bibliography notated music dataset (1650–2025) and creates descriptive visualisations for the Master's Thesis "Visualising Notated Music Metadata from the Latvian National Bibliography" conducted within the RTU studies program RHMDB Digital Humanities.

## Setup (Google Colab + Google Drive)
"""
import pandas as pd
import plotly.express as px

from google.colab import drive
drive.mount('/content/gdrive')

import os
os.chdir("/content/gdrive/MyDrive/magistrs/data")


"""## Load the dataset"""
df = pd.read_csv('notated-music-dataset.csv',sep=',', low_memory=False)
# change year collum as integer
df["full_year_008"] = df["full_year_008"].astype("Int64")

# checking the year column data type
df["full_year_008"].dtype

# renaminig the identification column
df = df.rename(columns={"ierakstu_id": "ID"})

# check how many records are there in the dateset by counting unique ID
df["ID"].nunique()

# create a copy of dataset where one row per bibliographic record (unique ID)
df_unique = df.drop_duplicates(subset=["ID"]).copy()


# Visualisations 
"""## Translation-related fields (041)"""

col_041a = "Language code of text/sound track or separate title (041_a)"
col_041e = "Language code of librettos(041_e)"
col_041h = "Language code of original(041_h)"

"""### The translated resource language (041a)"""

# using df because the language in which the resource is described can be repeated
lang_a_counts = (
    df[col_041a] # select the Language code of text/sound track or separate title (041_a) field
    .value_counts(dropna=True) # count the frequency of language
    .reset_index(name="count") # make a DataFrame with a 'count' column
)

fig = px.bar(
    lang_a_counts.head(15), # set values of top 15 languages
    x="count", # name x axis
    y="Language code of text/sound track or separate title (041_a)", # name y axis
    orientation="h",  # define chart orientation
    title="Top Languages of Translated Notated Music Materials (041$a)", # set chart title
    labels={"language": "Language code", "count": "Record count"}  # set chart labels

)
fig.show() # render chart

"""### Language of librettos (041_e)"""

# using df because the language of librettos can be repeated for record
libretto_counts = (
    df[col_041e] # select the Language code of librettos(041_e) field
    .value_counts(dropna=True)  # count the frequency of librettos language
    .reset_index(name="count") # make a DataFrame with a 'count' column
)

fig = px.bar(
    libretto_counts, # set values
    x="count", # name x axis
    y="Language code of librettos(041_e)", # name x axis
    orientation="h", # define chart orientation
    title="Libretto Languages in Notated Music (041$e)", # set chart title
    labels={"count": "Number of Records", "Language code of librettos(041_e)": "Libretto Language"}  # set chart labels
)
fig.show() # render chart

"""### Language of the original resource (041_h)"""

# using df because the original can be repeated for record
original_lang_counts = (
    df[col_041h] # select the Language code of original(041_h) field
    .value_counts(dropna=True) # count the frequency of each original language value
    .reset_index(name="count") # make a DataFrame with a 'count' column
)

fig = px.bar(
    original_lang_counts, # set values
    x="count", # name x axis
    y="Language code of original(041_h)", # name y axis
    orientation="h",
    title="Original Languages of Works in the Catalogue (041$h)", # set chart title
    labels={"count": "Number of Records", "Language code of original(041_h)": "Original Language"}  # set chart labels
)
fig.show() # render chart

"""### Translation Direction from the original to the published language"""

# selecting only records where both the original language and the language of the material are present
translation_df = df[df[col_041a].notna() & df[col_041h].notna()].copy()

translation_counts = (
    translation_df
    .groupby([col_041h, col_041a])["ID"] # grouping records by original language and material language
    .nunique() # count unique bibliographic records per languages pair
    .reset_index(name="count") # make a DataFrame with a 'count' column
)

fig = px.density_heatmap(
    translation_counts, # set values
    x=col_041h, # name x axis
    y=col_041a, # name y axis
    z="count", # define chart orientation
    title="Translation Directions in Notated Music (Original to Material Language)", # set chart title
    labels={ # set chart labels
        col_041a: "Language of Material (041$a)",
        col_041h: "Original Language (041$h)",
        "count": "Number of translations"
    },
    color_continuous_scale="Cividis"  # set colour for the scale
)
fig.update_layout(height=700) # set chart height
fig.show() # render chart
